### ISSUE TITLE
Inno Setup 5.6.1

### ISSUE THREAD

**Issue by TiltonJH** [vslavik/nuget-tools-innosetup#3]
There are new versions (5.6.0 and 5.6.1) of Inno Setup.

Can you please create and release the new nuget packages?

**Comment by vslavik** [comment]
I am well aware (not a complete incompetent, you know). Can *you* please show at the least the absolute minimal amount of courtesy and check for duplicates before you file bugging issues?

Better yet, don't bug and contribute productively — in particular, lend a hand to the person who created the #2 PR and help get it into mergeable state, or at least help with verification (see also there). That would be useful and would help get the update out sooner.

**Comment by TiltonJH** [comment]
Thanks for the warm welcome. I did not want to imply any incompetent whatsoever. What I did imply is that most people do have lives beyond work and might miss things on occasion. And therefore would welcome a friendly reminder.

Since closed issues are hidden by default and imply that a matter is closed and done, one does tend to ignore them. Furthermore an issue is usually simply an question, a subject, a theme or a topic of sorts and not necessary a bug report. To mark an issue as a bug or whatever else, that what "Labels" are for.

So it seem to me and IMHO that #2 should still be open and if so I would have found it, because I did actually look for open ones.

**Comment by vslavik** [comment]
> Thanks for the warm welcome.

A *contributor* (i.e. a person that contributes something useful) deserves a warm welcome; somebody that only wastes my time through their laziness and acts entitled less so. Compare: how *you* welcome a family member vs, say, a burglar.

> And therefore would welcome a friendly reminder.

I would certainly welcome friendly *help*. But "friendly reminder" is just code for bugging because you're under the impression that I have some sort of obligation to update this package.

> Furthermore an issue is usually simply an question, a subject, a theme or a topic of sorts and not necessary a bug report. To mark an issue as a bug or whatever else, that what "Labels" are for.

Thanks for the condescending lecture on how to use GitHub, your profile certainly shows deep familiarity. You're wrong, though: and issue is an actionable *issue*, not a discussion *forum*. Hence, you know, the freaking name of it.

> So it seem to me and IMHO that #2 should still be open and if so I would have found it, because I did actually look for open ones.

It *is* open and you very obviously didn't even bother to look.
